// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.string().name("room_id"),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  color: __t.string(),
  cursorX: __t.f64().name("cursor_x"),
  cursorY: __t.f64().name("cursor_y"),
  cursorTarget: __t.string().name("cursor_target"),
  lastSeen: __t.timestamp().name("last_seen"),
});
