// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.string().name("room_id"),
  assetId: __t.string().name("asset_id"),
  name: __t.string(),
  sizeBytes: __t.u64().name("size_bytes"),
  mimeType: __t.string().name("mime_type"),
  s3Url: __t.option(__t.string()).name("s_3_url"),
  uploadedBy: __t.identity().name("uploaded_by"),
});
