// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  creatorIdentity: __t.identity().name("creator_identity"),
  isPersistent: __t.bool().name("is_persistent"),
  createdAt: __t.timestamp().name("created_at"),
  lastActiveAt: __t.timestamp().name("last_active_at"),
});
