// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BoxState = __t.object("BoxState", {
  id: __t.u64(),
  roomId: __t.string(),
  boxUuid: __t.string(),
  boxName: __t.string(),
  data: __t.string(),
});
export type BoxState = __Infer<typeof BoxState>;

export const CleanupSchedule = __t.object("CleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CleanupSchedule = __Infer<typeof CleanupSchedule>;

export const Presence = __t.object("Presence", {
  id: __t.u64(),
  roomId: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  color: __t.string(),
  cursorX: __t.f64(),
  cursorY: __t.f64(),
  cursorTarget: __t.string(),
  lastSeen: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const Room = __t.object("Room", {
  id: __t.string(),
  creatorIdentity: __t.identity(),
  isPersistent: __t.bool(),
  createdAt: __t.timestamp(),
  lastActiveAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomAsset = __t.object("RoomAsset", {
  id: __t.u64(),
  roomId: __t.string(),
  assetId: __t.string(),
  name: __t.string(),
  sizeBytes: __t.u64(),
  mimeType: __t.string(),
  uploadedBy: __t.identity(),
});
export type RoomAsset = __Infer<typeof RoomAsset>;

export const RoomParticipant = __t.object("RoomParticipant", {
  id: __t.u64(),
  roomId: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  color: __t.string(),
  joinedAt: __t.timestamp(),
});
export type RoomParticipant = __Infer<typeof RoomParticipant>;

export const WebrtcSignal = __t.object("WebrtcSignal", {
  id: __t.u64(),
  roomId: __t.string(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  signalType: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type WebrtcSignal = __Infer<typeof WebrtcSignal>;

