// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BoxCreateReducer from "../box_create_reducer";
import BoxDeleteReducer from "../box_delete_reducer";
import BoxUpdateReducer from "../box_update_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import PingReducer from "../ping_reducer";
import PromoteRoomReducer from "../promote_room_reducer";
import RegisterAssetReducer from "../register_asset_reducer";
import SendSignalReducer from "../send_signal_reducer";
import UpdatePresenceReducer from "../update_presence_reducer";

export type BoxCreateParams = __Infer<typeof BoxCreateReducer>;
export type BoxDeleteParams = __Infer<typeof BoxDeleteReducer>;
export type BoxUpdateParams = __Infer<typeof BoxUpdateReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type PingParams = __Infer<typeof PingReducer>;
export type PromoteRoomParams = __Infer<typeof PromoteRoomReducer>;
export type RegisterAssetParams = __Infer<typeof RegisterAssetReducer>;
export type SendSignalParams = __Infer<typeof SendSignalReducer>;
export type UpdatePresenceParams = __Infer<typeof UpdatePresenceReducer>;

