import {describe, expect, it} from "vitest"
import {createFixture} from "./Fixture"

describe("Modulators", () => {
    it("creates every modulator kind with unique labels", () => {
        const {project} = createFixture()
        const lfo = project.addModulator("LFO", {shape: 2, rateSync: 6, phase: 0.5})
        const steps = project.addModulator("Steps", {count: 8})
        const macro = project.addModulator("Macro", {value: 0.75})
        const random = project.addModulator("Random", {seed: 42, levels: 4})
        const secondLfo = project.addModulator("LFO")
        expect(project.modulators.map(modulator => modulator.label)).toEqual(["LFO", "Steps", "Macro", "Random", "LFO 2"])
        expect(project.modulators.map(modulator => modulator.index)).toEqual([0, 1, 2, 3, 4])
        expect(lfo.shape).toBe(2)
        expect(lfo.rateSync).toBe(6)
        expect(lfo.phase).toBe(0.5)
        expect(lfo.bipolar).toBe(true)
        expect(lfo.amount).toBe(1)
        expect(steps.count).toBe(8)
        expect(macro.value).toBe(0.75)
        expect(random.seed).toBe(42)
        expect(random.levels).toBe(4)
        expect(secondLfo.kind).toBe("LFO")
        expect(() => lfo.shape = 9 as any).toThrow(RangeError)
        lfo.rateSync = 99
        expect(lfo.rateSync).toBe(12)
        expect(() => project.addModulator("Envelope" as any)).toThrow(RangeError)
    })

    it("edits step sequences", () => {
        const {project} = createFixture()
        const steps = project.addModulator("Steps")
        expect(steps.steps.length).toBe(64)
        expect(steps.steps[0]).toBe(0.5)
        steps.setSteps([0, 0.25, 0.5, 2])
        expect(steps.count).toBe(4)
        expect(Array.from(steps.steps.slice(0, 4))).toEqual([0, 0.25, 0.5, 1])
        expect(() => steps.setSteps(new Array(65).fill(0))).toThrow(RangeError)
        expect(() => steps.setSteps("abc" as any)).toThrow(TypeError)
        steps.direction = 4
        expect(steps.direction).toBe(4)
    })

    it("assigns modulators to parameters", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        const lfo = project.addModulator("LFO")
        const modulation = lfo.assign(unit.instrument, "cutoff", 0.5)
        expect(modulation.source).toBe(lfo)
        expect(modulation.target).toBe(unit.instrument)
        expect(modulation.parameter).toBe("cutoff")
        expect(modulation.depth).toBe(0.5)
        expect(modulation.enabled).toBe(true)
        const nested = lfo.assign(unit.instrument, "lfo.rate")
        expect(nested.depth).toBe(0.25)
        expect(nested.parameter).toBe("lfo.rate")
        const strip = lfo.assign(unit, "panning", -2)
        expect(strip.depth).toBe(-1)
        expect(lfo.modulations.length).toBe(3)
        expect(() => lfo.assign(unit.instrument, "label" as any)).toThrow(RangeError)
        expect(() => lfo.assign(lfo as any, "phase")).toThrow(RangeError)
        modulation.remove()
        expect(lfo.modulations.length).toBe(2)
        lfo.remove()
        expect(project.modulators.length).toBe(0)
        expect(() => nested.depth).toThrow()
    })

    it("automates modulator parameters and assignment depths", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        const lfo = project.addModulator("LFO")
        const other = project.addModulator("Macro")
        const modulation = lfo.assign(unit.instrument, "cutoff")
        const rate = lfo.addValueTrack(lfo, "rateAbsolute")
        expect(rate.type).toBe("value")
        expect(rate.owner).toBe(lfo)
        expect(rate.audioUnit).toBeNull()
        expect(rate.target).toBe(lfo)
        expect(rate.parameter).toBe("rateAbsolute")
        const depth = lfo.addValueTrack(modulation, "depth")
        expect(depth.target).toBe(modulation)
        expect(depth.parameter).toBe("depth")
        expect(lfo.valueTracks).toEqual([rate, depth])
        expect(rate.index).toBe(0)
        expect(depth.index).toBe(1)
        depth.addRegion().addEvent({value: 0.5})
        expect(() => lfo.addValueTrack(lfo, "rateAbsolute")).toThrow(RangeError)
        expect(() => lfo.addValueTrack(other, "value")).toThrow(RangeError)
        expect(() => lfo.addValueTrack(lfo, "label" as any)).toThrow(RangeError)
        expect(() => unit.addValueTrack(lfo as any, "rateAbsolute")).not.toThrow()
        rate.remove()
        expect(depth.index).toBe(0)
        lfo.remove()
        expect(() => depth.enabled).toThrow()
    })
})
