// GENERATED by ar-303 scripts/export_parity_vectors.mjs - do not edit.
// Model: final
pub struct Ev {pub at: usize, pub off: bool, pub note: f64, pub accent: bool, pub slide: bool}
pub struct Case {pub name: &'static str, pub blocks: usize, pub params: Params, pub events: &'static [Ev]}
pub const MODEL: &str = "final";
pub const SAMPLE_RATE: f64 = 48000.0;
pub const BLOCK: usize = 8;
pub const CASES: &[Case] = &[
    Case {
        name: "plain_note",
        blocks: 3000,
        params: Params {tuning: 0.5, waveform: 0.0, cutoff: 0.5, resonance: 0.0, envmod: 0.0, decay: 0.5, accent: 0.0, volume: 0.8},
        events: &[Ev {at: 0, off: false, note: 36.0, accent: false, slide: false}, Ev {at: 1500, off: true, note: 0.0, accent: false, slide: false}]
    },
    Case {
        name: "resonant_note",
        blocks: 3000,
        params: Params {tuning: 0.5, waveform: 0.0, cutoff: 0.3, resonance: 0.9, envmod: 0.0, decay: 0.5, accent: 0.0, volume: 0.8},
        events: &[Ev {at: 0, off: false, note: 36.0, accent: false, slide: false}, Ev {at: 1500, off: true, note: 0.0, accent: false, slide: false}]
    },
    Case {
        name: "envelope_sweep",
        blocks: 3000,
        params: Params {tuning: 0.5, waveform: 0.0, cutoff: 0.15, resonance: 0.7, envmod: 0.9, decay: 0.2, accent: 0.0, volume: 0.8},
        events: &[Ev {at: 0, off: false, note: 40.0, accent: false, slide: false}, Ev {at: 1500, off: true, note: 0.0, accent: false, slide: false}]
    },
    Case {
        name: "accent_single",
        blocks: 3000,
        params: Params {tuning: 0.5, waveform: 0.0, cutoff: 0.15, resonance: 0.9, envmod: 0.15, decay: 0.3, accent: 0.7, volume: 0.8},
        events: &[Ev {at: 0, off: false, note: 36.0, accent: true, slide: false}, Ev {at: 1500, off: true, note: 0.0, accent: false, slide: false}]
    },
    Case {
        name: "slide_chain",
        blocks: 4000,
        params: Params {tuning: 0.5, waveform: 0.0, cutoff: 0.15, resonance: 0.9, envmod: 0.15, decay: 0.3, accent: 0.7, volume: 0.8},
        events: &[Ev {at: 0, off: false, note: 36.0, accent: false, slide: false}, Ev {at: 600, off: false, note: 43.0, accent: false, slide: true}, Ev {at: 1200, off: false, note: 36.0, accent: false, slide: true}, Ev {at: 2000, off: true, note: 0.0, accent: false, slide: false}]
    },
    Case {
        name: "accent_depletion",
        blocks: 5000,
        params: Params {tuning: 0.5, waveform: 0.0, cutoff: 0.0, resonance: 1.0, envmod: 0.0, decay: 0.0, accent: 1.0, volume: 0.8},
        events: &[Ev {at: 0, off: false, note: 36.0, accent: true, slide: false}, Ev {at: 400, off: false, note: 38.0, accent: true, slide: true}, Ev {at: 800, off: false, note: 36.0, accent: true, slide: true}, Ev {at: 1200, off: true, note: 0.0, accent: false, slide: false}, Ev {at: 2400, off: false, note: 36.0, accent: true, slide: false}, Ev {at: 3000, off: true, note: 0.0, accent: false, slide: false}]
    },
    Case {
        name: "square_wave",
        blocks: 3000,
        params: Params {tuning: 0.5, waveform: 1.0, cutoff: 0.4, resonance: 0.6, envmod: 0.5, decay: 0.4, accent: 0.5, volume: 0.8},
        events: &[Ev {at: 0, off: false, note: 36.0, accent: true, slide: false}, Ev {at: 1500, off: true, note: 0.0, accent: false, slide: false}]
    }
];
