// 🤖 AUTO-GENERATED BY GOLDEN STANDARD GENERATOR (V2)
// DO NOT EDIT MANUALLY.
// Quality: World Class (Izotope/Waves Standard)

import { SchoolLesson } from "./OdieSchoolData";

export const GENERATED_CURRICULUM: SchoolLesson[] = [
    {
    "id": "mix-1",
    "title": "Gain Staging: The 0dB Rule",
    "category": "mixing",
    "desc": "Why your mix sounds distorted before you even start.",
    "tags": [
        "mixing",
        "generated",
        "v2"
    ],
    "content": "\n# Gain Staging: The 0dB Rule\n> \"If you clip at the input, no plugin can save you.\"\n\n## 🧠 Why your mix sounds distorted before you even start.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Input Gain** | The volume entering the plugin. |\n| **Output Gain** | The volume leaving the plugin. |\n| **Clip Light** | Red means dead. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Source Audio] -->|Too Hot!| B(Input Gain: -6dB)\n    B -->|Clean Signal| C[Compressor]\n    C -->|Makeup Gain| D[Output]\n```\n\n## 🛠️ Actionable Steps\n1.  Select every channel in the mixer.\n2.  Pull faders down to -∞.\n2.  Bring up the Kick Drum to -6dB peak.\n2.  Bring in other elements around it.\n\n## 🎸 Application Context\n*   **Vocals**: Keep peaks around -10dB recording.\n*   **Synths**: VSTs are loud. Turn them down initially.\n\n> **⚠️ Common Mistake**: Thinking red lights are 'warmth'. In digital, they are just math errors.\n\n> **💡 Pro Tip**: Use a dedicated 'Trim' or 'Utility' plugin as the first slot on every channel to manage gain automation without touching your faders.\n"
},
    {
    "id": "mix-2",
    "title": "EQ: Subtractive Synthesis",
    "category": "mixing",
    "desc": "Cutting the mud to find the clarity.",
    "tags": [
        "mixing",
        "generated",
        "v2"
    ],
    "content": "\n# EQ: Subtractive Synthesis\n> \"You don't need to boost the highs. You need to cut the lows.\"\n\n## 🧠 Cutting the mud to find the clarity.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Frequency (Hz)** | The pitch you are affecting. |\n| **Gain (dB)** | How much you boost or cut. |\n| **Q (Width)** | Narrow (surgical) or Wide (musical). |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Muddy Vocal] -->|Cut 200Hz| B(EQ)\n    B -->|Clear Vocal| C[Compressor]\n```\n\n## 🛠️ Actionable Steps\n1.  Listen to the track in solo.\n2.  Boost a narrow band (High Q) and sweep until it sounds terrible.\n2.  Cut that frequency by -3dB to -6dB.\n\n## 🎸 Application Context\n*   **Vocals**: Low cut at 100Hz to remove rumble.\n*   **Guitars**: Cut 300-400Hz to remove 'boxiness'.\n\n> **⚠️ Common Mistake**: Boosting everything because it 'sounds better' louder.\n\n> **💡 Pro Tip**: Cut narrow, boost wide. Surgical cuts remove problems; wide boosts add character.\n"
},
    {
    "id": "mix-3",
    "title": "Compression: The Handshake",
    "category": "mixing",
    "desc": "Controlling dynamics and adding punch.",
    "tags": [
        "mixing",
        "generated",
        "v2"
    ],
    "content": "\n# Compression: The Handshake\n> \"Ideally, you shouldn't hear it working. You should just feel it.\"\n\n## 🧠 Controlling dynamics and adding punch.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Threshold** | The volume level where compression starts. |\n| **Ratio** | How much volume is reduced (4:1 means 4dB in = 1dB out). |\n| **Attack** | How fast it reacts to a transient. |\n| **Release** | How fast it lets go. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Dynamic Audio] -->|Crosses Threshold| B(Compressor)\n    B -->|Gain Reduction| C[Consistent Output]\n```\n\n## 🛠️ Actionable Steps\n1.  Set Ratio to 4:1.\n2.  Lower Threshold until you see -3dB to -6dB of Gain Reduction.\n2.  Adjust Attack to let the transient punch (slower) or clamp down (faster).\n2.  Adjust Release to 'breathe' with the tempo.\n\n## 🎸 Application Context\n*   **Drums**: Slow attack (30ms) lets the stick hit through. Fast release makes it pump.\n*   **Vocals**: Fast attack tames peaks. Medium release keeps it smooth.\n\n> **⚠️ Common Mistake**: Over-compressing until the life is sucked out.\n\n> **💡 Pro Tip**: Parallel Compression (New York Style): Mix a heavily compressed signal with the dry signal for the best of both worlds.\n"
},
    {
    "id": "mix-4",
    "title": "Reverb: Creating Space",
    "category": "mixing",
    "desc": "Placing your sound in a 3D environment.",
    "tags": [
        "mixing",
        "generated",
        "v2"
    ],
    "content": "\n# Reverb: Creating Space\n> \"Dry sounds are 'in your face'. Reverb puts them 'in a room'.\"\n\n## 🧠 Placing your sound in a 3D environment.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Decay Time** | How long the tail lasts. |\n| **Pre-Delay** | Gap between dry sound and reverb start. |\n| **Wet/Dry** | The blend. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Dry Vocal] -->|Send| B(Reverb Aux)\n    A -->|Direct| C[Master]\n    B -->|Wet Signal| C\n```\n\n## 🛠️ Actionable Steps\n1.  Create an Aux/Send track with a Reverb plugin (100% Wet).\n2.  Send your instrument to this track.\n2.  Adjust the Send level to place the instrument 'further back'.\n\n## 🎸 Application Context\n*   **Snare**: Plate reverb (1.5s) works great for classic rock.\n*   **Vocals**: Use Pre-Delay (60ms) to keep the vocal upfront while adding space.\n\n> **⚠️ Common Mistake**: Putting Reverb directly on the track insert (blurry mix).\n\n> **💡 Pro Tip**: EQ your Reverb. Low-cut the reverb return at 200Hz-400Hz to keep the mix clean.\n"
},
    {
    "id": "mix-5",
    "title": "Delay: Rhythmic Echoes",
    "category": "mixing",
    "desc": "Adding depth and groove without the wash of reverb.",
    "tags": [
        "mixing",
        "generated",
        "v2"
    ],
    "content": "\n# Delay: Rhythmic Echoes\n> \"Reverb is a wash. Delay is a rhythm.\"\n\n## 🧠 Adding depth and groove without the wash of reverb.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Time** | Subdivision (1/4 note, 1/8 note). |\n| **Feedback** | Number of repeats. |\n| **Ping Pong** | Bouncing Left and Right. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Source] -->|Send| B(Delay)\n    B -->|Feedback Loop| B\n    B -->|Output| C[Mix]\n```\n\n## 🛠️ Actionable Steps\n1.  Sync Delay to Tempo.\n2.  Set to 1/4 note or 1/8 dotted.\n2.  Adjust Feedback so it fades out naturally.\n\n## 🎸 Application Context\n*   **Guitars**: Slapback (100ms) adds instant vintage vibe.\n*   **Vocals**: Throw delays on specific words for emphasis.\n\n> **⚠️ Common Mistake**: Delay times that fight the groove of the song.\n\n> **💡 Pro Tip**: Sidechain your Delay. Duck the delay volume when the vocal is singing, and let it bloom when the singer stops.\n"
},
    {
    "id": "write-1",
    "title": "Melody: The King",
    "category": "songwriting",
    "desc": "Why we hum.",
    "tags": [
        "songwriting",
        "generated",
        "v2"
    ],
    "content": "\n# Melody: The King\n> \"A great production can't save a bad melody.\"\n\n## 🧠 Why we hum.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Interval** | Distance between notes. |\n| **Rhythm** | When the notes hit. |\n| **Contour** | The shape (rising, falling). |\n\n## 🚦 Signal Flow\n```mermaid\ngraph TD\n    A[Idea] --> B{Step or Skip?}\n    B -->|Step| C(Smooth)\n    B -->|Skip| D(Energetic)\n    C --> E[Motif]\n    D --> E\n```\n\n## 🛠️ Actionable Steps\n1.  Start with a simple 3-4 note motif.\n2.  Repeat it but change the ending.\n2.  Keep it within a singable range.\n\n## 🎸 Application Context\n*   **Vocals**: Short phrases create space for the listener to digest.\n*   **Leads**: Use large interval jumps for emotional impact.\n\n> **⚠️ Common Mistake**: Too many notes (noodling).\n\n> **💡 Pro Tip**: Call and Response. Phrase A asks a question (ends on unstable note), Phrase B answers it (resolves to root).\n"
},
    {
    "id": "prod-1",
    "title": "Drum Programming: The Pocket",
    "category": "production",
    "desc": "Making MIDI drums feel human.",
    "tags": [
        "production",
        "generated",
        "v2"
    ],
    "content": "\n# Drum Programming: The Pocket\n> \"Computers are perfect. Humans are groovy.\"\n\n## 🧠 Making MIDI drums feel human.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Velocity** | How hard the drum is hit. |\n| **Quantize** | Locking to grid. |\n| **Swing** | Offsetting the off-beats. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[MIDI Note] -->|Velocity| B(Sampler)\n    B -->|Layering| C(Kick Top + Sub)\n    C -->|Bus Processing| D[Drum Bus]\n```\n\n## 🛠️ Actionable Steps\n1.  Program the main beat on the grid.\n2.  Select Hi-Hats and randomize velocity slightly.\n2.  Shift the Snare slightly late (5-10ms) for a laid-back feel.\n\n## 🎸 Application Context\n*   **Hi-Hats**: Vary velocity on every hit to simulate a real drummer's hand.\n*   **Ghost Notes**: Add very quiet snare hits in between backbeats.\n\n> **⚠️ Common Mistake**: 100% Velocity on everything (Machine Gun effect).\n\n> **💡 Pro Tip**: Layer your samples. Use one kick for the 'click' (attack) and another for the 'thump' (sub).\n"
},
    {
    "id": "master-1",
    "title": "The Limiter: The Ceiling",
    "category": "mastering",
    "desc": "Making it loud without breaking it.",
    "tags": [
        "mastering",
        "generated",
        "v2"
    ],
    "content": "\n# The Limiter: The Ceiling\n> \"The final guard at the door.\"\n\n## 🧠 Making it loud without breaking it.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Ceiling** | The absolute maximum volume (set to -0.1dB). |\n| **Threshold** | Pushing the volume into the ceiling. |\n| **Release** | Recovery speed. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Final Mix] --> B[Master EQ]\n    B --> C[Master Comp]\n    C --> D[Limiter]\n    D --> E[Streaming Service]\n```\n\n## 🛠️ Actionable Steps\n1.  Set Ceiling to -1.0dB (True Peak safety).\n2.  Lower Threshold until you reach competitive loudness (-14 LUFS to -9 LUFS).\n2.  Listen for distortion.\n\n## 🎸 Application Context\n*   **Full Mix**: If the limiter is working hard (-4dB gain reduction), go back to the mix.\n\n> **⚠️ Common Mistake**: Crushing the dynamics for pure volume.\n\n> **💡 Pro Tip**: Check your master in mono and on a phone speaker. If the vocal disappears, the limiter might be pushing it down.\n"
},
    {
    "id": "theory-1",
    "title": "The Major Scale",
    "category": "theory",
    "desc": "The DNA of Western music.",
    "tags": [
        "theory",
        "generated",
        "v2"
    ],
    "content": "\n# The Major Scale\n> \"Do Re Mi Fa Sol La Ti Do.\"\n\n## 🧠 The DNA of Western music.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **W** | Whole Step (2 semitones). |\n| **H** | Half Step (1 semitone). |\n| **Root** | The home note. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Root] -->|W| B[2nd]\n    B -->|W| C[3rd]\n    C -->|H| D[4th]\n    D -->|W| E[5th]\n    E -->|W| F[6th]\n    F -->|W| G[7th]\n    G -->|H| H[Octave]\n```\n\n## 🛠️ Actionable Steps\n1.  Pick a note (C).\n2.  Follow the formula: W-W-H-W-W-W-H.\n2.  Example: C -> D -> E -> F -> G -> A -> B -> C.\n\n## 🎸 Application Context\n*   **Piano**: C Major is all white keys.\n*   **Bass**: Learn the scale shape to walk basslines.\n\n> **⚠️ Common Mistake**: Memorizing note names instead of the interval formula.\n\n> **💡 Pro Tip**: The Relative Minor contains the exact same notes. C Major = A Minor.\n"
},
    {
    "id": "prod-2",
    "title": "Bass Design: The Foundation",
    "category": "production",
    "desc": "Holding down the low end.",
    "tags": [
        "production",
        "generated",
        "v2"
    ],
    "content": "\n# Bass Design: The Foundation\n> \"If the bass is weak, the track is weak.\"\n\n## 🧠 Holding down the low end.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Oscillator** | Waveform choice (Sine vs Saw). |\n| **Filter** | Removing high frequencies. |\n| **Envelope** | Shape of the note. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Oscillator] --> B(Low Pass Filter)\n    B --> C(Mono Utility)\n    C --> D[Output]\n```\n\n## 🛠️ Actionable Steps\n1.  Use a Sine or Triangle wave for sub-bass.\n2.  Use a Saw wave for texture/grit.\n2.  Always keep frequencies below 100Hz in Mono.\n\n## 🎸 Application Context\n*   **Sub Bass**: Pure sine wave at 40-60Hz hits the chest.\n*   **Reese Bass**: Detune two saw waves for movement.\n\n> **⚠️ Common Mistake**: Too much stereo width on sub-bass (causing phase issues).\n\n> **💡 Pro Tip**: Sine Compression: Heavily compress your sine sub to make it a solid brick of low end.\n"
},
    {
    "id": "prod-3",
    "title": "Synth Leads: Cutting Through",
    "category": "production",
    "desc": "Designing sounds that demand attention.",
    "tags": [
        "production",
        "generated",
        "v2"
    ],
    "content": "\n# Synth Leads: Cutting Through\n> \"The lead is the voice of the instrumental.\"\n\n## 🧠 Designing sounds that demand attention.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Detune** | Pitch drift for thickness. |\n| **Glide/Portamento** | Sliding between notes. |\n| **Unison** | Stacking multiple voices. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Oscillator] --> B(Unison Stack)\n    B --> C(Distortion)\n    C --> D[Reverb/Delay]\n```\n\n## 🛠️ Actionable Steps\n1.  Start with a Saw or Square wave.\n2.  Add a little Glide (50ms) for legato playing.\n2.  Add saturation to help it cut through the mix.\n\n## 🎸 Application Context\n*   **EDM Lead**: Use 'Super Saw' stacking for massive width.\n*   **Funk Lead**: Use a simple mono saw with fast glide.\n\n> **⚠️ Common Mistake**: Drowning the lead in too much reverb (pushes it back).\n\n> **💡 Pro Tip**: Use 'OTR' (Over The Top) compression to bring out the fizzy high-end details.\n"
},
    {
    "id": "mix-6",
    "title": "Saturation: The Color",
    "category": "mixing",
    "desc": "Adding harmonic richness.",
    "tags": [
        "mixing",
        "generated",
        "v2"
    ],
    "content": "\n# Saturation: The Color\n> \"Digital is clean. Analog is dirty. We want dirty.\"\n\n## 🧠 Adding harmonic richness.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Drive** | Input gain (distortion amount). |\n| **Type** | Tube, Tape, or Transistor. |\n| **Mix** | Blending clean and dirty. |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Clean Audio] --> B(Saturation)\n    B -->|Harmonics Added| C[Rich Audio]\n```\n\n## 🛠️ Actionable Steps\n1.  Apply saturation to the Drum Bus.\n2.  Increase Drive until it sounds crunchy, then back off slightly.\n2.  Listen to how it 'glues' the sound together.\n\n## 🎸 Application Context\n*   **808s**: Distortion makes sub-bass audible on small speakers.\n*   **Vocals**: Light tube saturation adds warmth and presence.\n\n> **⚠️ Common Mistake**: Destroying the transients with too much drive.\n\n> **💡 Pro Tip**: Tape Saturation rolls off high frequencies naturally, making digital synths sound more organic.\n"
},
    {
    "id": "mix-7",
    "title": "Stereo Width: The Sides",
    "category": "mixing",
    "desc": "Making the mix feel huge.",
    "tags": [
        "mixing",
        "generated",
        "v2"
    ],
    "content": "\n# Stereo Width: The Sides\n> \"Contrast is key. If everything is wide, nothing is wide.\"\n\n## 🧠 Making the mix feel huge.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Width** | Side signal volume. |\n| **Mid/Side** | Processing center vs edges. |\n| **Correlation** | Phase check (+1 is good, -1 is bad). |\n\n## 🚦 Signal Flow\n```mermaid\ngraph TD\n    A[Input] --> B{Split}\n    B --> C[Mid (Mono)]\n    B --> D[Side (Diff)]\n    D -->|Boost| E[Wide Output]\n```\n\n## 🛠️ Actionable Steps\n1.  Keep the Kick, Snare, Bass, and Lead Vocal in the Center (Mono).\n2.  Pan Guitars, Synths, and Backing Vocals hard Left/Right.\n2.  Use a Widener on the Master Bus (sparingly).\n\n## 🎸 Application Context\n*   **Context**: Make the verses narrower and the choruses wider for impact.\n\n> **⚠️ Common Mistake**: Widening the low end (causes phase cancellation).\n\n> **💡 Pro Tip**: Haas Effect: Delay one channel by 10-20ms to create artificial width (but check mono!).\n"
},
    {
    "id": "theory-2",
    "title": "The Minor Scale",
    "category": "theory",
    "desc": "The emotional counterpart.",
    "tags": [
        "theory",
        "generated",
        "v2"
    ],
    "content": "\n# The Minor Scale\n> \"Sad, serious, or epic.\"\n\n## 🧠 The emotional counterpart.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Pattern** | W-H-W-W-H-W-W |\n| **3rd** | Flat 3rd (Minor 3rd). |\n| **7th** | Flat 7th (Minor 7th). |\n\n## 🚦 Signal Flow\n```mermaid\ngraph LR\n    A[Root] -->|W| B[2nd]\n    B -->|H| C[b3rd]\n    C -->|W| D[4th]\n    D -->|W| E[5th]\n    E -->|H| F[b6th]\n    F -->|W| G[b7th]\n```\n\n## 🛠️ Actionable Steps\n1.  Lower the 3rd, 6th, and 7th notes of a Major scale.\n2.  C Major: C D E F G A B\n2.  C Minor: C D Eb F G Ab Bb\n\n## 🎸 Application Context\n*   **Trap Music**: Almost exclusively uses Minor or Phrygian scales.\n\n> **⚠️ Common Mistake**: Avoiding the minor scale because it's 'sad'. It's also 'powerful'.\n\n> **💡 Pro Tip**: Harmonic Minor: Raise the 7th note back up to create tension/resolution (the 'Snake Charmer' sound).\n"
},
    {
    "id": "theory-3",
    "title": "Chords: Stacking Notes",
    "category": "theory",
    "desc": "Harmony basics.",
    "tags": [
        "theory",
        "generated",
        "v2"
    ],
    "content": "\n# Chords: Stacking Notes\n> \"One note is a line. Three notes are a shape.\"\n\n## 🧠 Harmony basics.\n\n## 🎛️ The Controls\nBefore you turn the knobs, understand them.\n\n| Parameter | Definition |\n| :--- | :--- |\n| **Triad** | Root, 3rd, 5th. |\n| **Major** | Happy (Major 3rd). |\n| **Minor** | Sad (Minor 3rd). |\n\n## 🚦 Signal Flow\n```mermaid\ngraph TD\n    A[Root] --> B[3rd]\n    B --> C[5th]\n    C --> D[Chord]\n```\n\n## 🛠️ Actionable Steps\n1.  Pick a note (Root).\n2.  Skip a scale note to find the 3rd.\n2.  Skip another scaling note to find the 5th.\n\n## 🎸 Application Context\n*   **Pads**: Use 7th and 9th chords for lush, expensive sounds.\n\n> **⚠️ Common Mistake**: Using only triads (can sound cheap/basic).\n\n> **💡 Pro Tip**: Inversions: Change the order of notes (e.g., C-E-G becomes E-G-C) to make chord changes smoother.\n"
},

];
